### ISSUE TITLE
Unsupported data type .

### ISSUE THREAD

**Issue by tiandeyu** [emqx/kuiper#295]
I change edgex integration message bus from default zmq to mqtt, comment below in edgex.yaml.

Error "Unsupported data type ." shows when I send data to mqtt broker which kuiper subscribed.

message:

```json
{
  "device": "MTPLC",
  "origin": 1591602946824502000,
  "readings": [
    {
      "origin": 1591602946815001900,
      "device": "MTPLC",
      "name": "SpindleMotorPower",
      "value": "5.683000e-01"
    },
    {
      "origin": 1591602946818082300,
      "device": "MTPLC",
      "name": "TotalPower",
      "value": "4.506000e-01"
    }
  ]
}
```

stream:
```
{"sql":"create stream edgebox2 () WITH ( type = \"edgex\", FORMAT = \"json\" )"}
```
rule:
```
{
  "id": "ruleEdgebox2",
  "sql": "SELECT * from edgebox2",
  "actions": [
    {
      "log": {}
    }
  ]
}
```

edgex.yaml,  cat edgex.yaml
```
#Global Edgex configurations
default:
  protocol: tcp
  server: 192.168.3.105
  port: 1883
  topic: central/edgebox2
  serviceServer: http://192.168.3.105:48080
#  Below is optional configurations settings for mqtt
  type: mqtt
  optional:
    ClientId: "clientkuiper"
#    Username: user1
#    Password: password
#    Qos: 1
#    KeepAlive: 5000
#    Retained: true/false
#    ConnectionPayload:
#    CertFile:
#    KeyFile:
#    CertPEMBlock:
#    KeyPEMBlock:
#    SkipCertVerify: true/false

#Override the global configurations
application_conf: #Conf_key
  protocol: tcp
  server: localhost
  port: 5571
  topic: application

mqtt_conf: #Conf_key
  protocol: tcp
  server: 192.168.3.105
  port: 1883
  topic: central/edgebox2
  type: mqtt
  optional:
    ClientId: "clientkuiper"
```
Log file
```
time="2020-06-08T08:44:54Z" level=info msg="Stream edgebox2 is created." file="xsql_processor.go:75"
time="2020-06-08T08:45:03Z" level=info msg="Rule ruleEdgebox2 is created." file="xsql_processor.go:226"
time="2020-06-08T08:45:03Z" level=info msg="Init rule with options {isEventTime: false, lateTolerance: 0, concurrency: 1, bufferLength: 1024" file="xsql_processor.go:399"
time="2020-06-08T08:45:03Z" level=info msg="Opening stream" file="streams.go:89" rule=ruleEdgebox2
time="2020-06-08T08:45:03Z" level=debug msg="open sink node log_0" file="sink_node.go:68" rule=ruleEdgebox2
time="2020-06-08T08:45:03Z" level=debug msg="Unary operator preprocessor_edgebox2 is started" file="operations.go:80" rule=ruleEdgebox2
time="2020-06-08T08:45:03Z" level=debug msg="Unary operator project is started" file="operations.go:80" rule=ruleEdgebox2
time="2020-06-08T08:45:03Z" level=info msg="open source node edgebox2 with option map[FORMAT:json TYPE:edgex]" file="source_node.go:59" rule=ruleEdgebox2
time="2020-06-08T08:45:03Z" level=info msg="open sink node 1 instances" file="sink_node.go:143" rule=ruleEdgebox2
time="2020-06-08T08:45:03Z" level=info msg="Opening func collector" file="func.go:36" rule=ruleEdgebox2
time="2020-06-08T08:45:03Z" level=debug msg="cache saved to /usr/local/kuiper/data/sink" file="sink_cache.go:90" rule=ruleEdgebox2
time="2020-06-08T08:45:03Z" level=debug msg="get conf for edgex with conf key : map[optional:map[ClientId:clientkuiper] port:1883 protocol:tcp server:192.168.3.105 serviceServer:http://192.168.3.105:48080 topic:central/edgebox2 type:mqtt]" file="source_node.go:219" rule=ruleEdgebox2
time="2020-06-08T08:45:03Z" level=info msg="open source node 1 instances" file="source_node.go:78" rule=ruleEdgebox2
time="2020-06-08T08:45:03Z" level=info msg="Connect to value descriptor service at: http://192.168.3.105:48080/api/v1/valuedescriptor \n" file="edgex_source.go:59"
time="2020-06-08T08:45:03Z" level=info msg="Use configuration for edgex messagebus {{ 0 } {192.168.3.105 1883 tcp} mqtt map[]}\n" file="edgex_source.go:67"
time="2020-06-08T08:45:03Z" level=info msg="Start source edgebox2 instance 0 successfully" file="source_node.go:115" rule=ruleEdgebox2
time="2020-06-08T08:45:03Z" level=info msg="The connection to edgex messagebus is established successfully." file="edgex_source.go:116" rule=ruleEdgebox2
time="2020-06-08T08:45:03Z" level=info msg="Successfully subscribed to edgex messagebus topic central/edgebox2." file="edgex_source.go:125" rule=ruleEdgebox2
time="2020-06-08T08:45:33Z" level=error msg="Unsupported data type ." file="edgex_source.go:184" rule=ruleEdgebox2
```
