### ISSUE TITLE
Update EdgeX environment variable

### ISSUE THREAD

**Issue by zhanghongtong** [emqx/kuiper#394]
About https://github.com/emqx/kuiper/pull/393

**Comment by jinfahua** [comment]
Below is one of example that was tested.

```
  rulesengine:
    image: emqx/kuiper:0.9.0-90-ga967146-slim
    ports:
      - "9081:48075"
      - "127.0.0.1:20498:20498"
    container_name: edgex-kuiper
    hostname: edgex-kuiper
    networks:
      - edgex-network
    environment:
      # KUIPER_DEBUG: "true"
      KUIPER__BASIC__CONSOLELOG: "true"
      KUIPER__BASIC__RESTPORT: 48075
      KUIPER__BASIC__PLUGINHOSTS: http://52.53.170.189
      EDGEX__DEFAULT__SERVER: edgex-app-service-configurable-rules
      EDGEX__DEFAULT__SERVICESERVER: http://edgex-core-data:48080
      EDGEX__DEFAULT__TOPIC: events
      EDGEX__DEFAULT__PROTOCOL: tcp
      EDGEX__DEFAULT__PORT: 5566
    depends_on:
      - app-service-rules
```
