### ISSUE TITLE
Kuiper gives error when configured to use redisstreams for EdgeX MessageBus

### ISSUE THREAD

**Issue by lenny-intel** [emqx/kuiper#549]
The EdgeX MessageBus has a `redisstreams` implementation. When I configure Kuiper 0.9.1 to use `redisstreams` type for the EdgeX MessageBus I get the following error:

```
time="2020-10-08T23:44:29Z" level=info msg="closing rule ruleBool for error: Specified wrong message type value redisstreams, will use zeromq messagebus.\n" file="entry.go:314"
```

Looks like you have a check that doesn't like anything except `zero` or `mqtt`. Note that the message bus `NewMessageClient` will return an error if the type is not supported, so you don't have to have your own check.

My Kuiper configuration in the compose file is:
```
    environment:
      KUIPER_DEBUG: "true"
      KUIPER_CONSOLE_LOG: "true"
      KUIPER_REST_PORT: 48075
      EDGEX_SERVICE_SERVER: http://edgex-core-data:48080
      EDGEX__DEFAULT__SERVER: edgex-redis
      EDGEX__DEFAULT__TOPIC: rules-events
      EDGEX__DEFAULT__PORT: 6379
      EDGEX__DEFAULT__TYPE: redisstreams
      EDGEX__DEFAULT__PROTOCOL: redis
```

Kuiper logs show that Kuiper is using the setting:
```
default:
  port: 6379
  protocol: redis
  server: edgex-redis
  serviceServer: http://localhost:48080
  topic: rules-events
  type: redisstreams
```
